export const classLevelOptions = [
    { label: 'Pre-K', value: 'pre_k' },
    { label: 'Kindergarten', value: 'kindergarten' },
    { label: '1st Grade', value: '1st' },
    { label: '2nd Grade', value: '2nd' },
    { label: '3rd Grade', value: '3rd' },
    { label: '4th Grade', value: '4th' },
    { label: '5th Grade', value: '5th' },
    { label: '6th Grade', value: '6th' },
    { label: '7th Grade', value: '7th' },
    { label: '8th Grade', value: '8th' },
    { label: '9th Grade', value: '9th' },
    { label: '10th Grade', value: '10th' },
    { label: '11th Grade', value: '11th' },
    { label: '12th Grade', value: '12th' },
    { label: 'Undergraduate Year 1', value: 'undergraduate_year_1' },
    { label: 'Undergraduate Year 2', value: 'undergraduate_year_2' },
    { label: 'Undergraduate Year 3', value: 'undergraduate_year_3' },
    { label: 'Undergraduate Year 4', value: 'undergraduate_year_4' },
    { label: 'Graduate Year 1', value: 'graduate_year_1' },
    { label: 'Graduate Year 2', value: 'graduate_year_2' },
    { label: 'PhD', value: 'phd' },
    { label: 'Adult Education', value: 'adult_education' },
];
